version: '3.9'

services:
  web: 
    container_name: jinrowebcont
    build:
      dockerfile: web/Dockerfile
      context: .
    ports:
      - 3000:3000
    networks:
      frontend:
        ipv4_address: 192.168.10.5
    tty: true
  app: 
    container_name: jinroappcont
    build:
      dockerfile: app/Dockerfile
      context: .
    ports:
      - 8080:8080
    networks:
      frontend:
        ipv4_address: 192.168.10.8
      backend:
        ipv4_address: 192.168.20.8
    tty: true
  db: 
    container_name: jinrodbcont
    build:
      dockerfile: db/Dockerfile
      context: .
    ports:
      - 5432:5432
    networks:
      backend:
        ipv4_address: 192.168.20.10
    tty: true

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
