version: '3.9'

services:
  web: 
    container_name: jinrowebcont
    build:
      dockerfile: web/Dockerfile
      context: .
    ports:
      - 3000:3000
    tty: true
  app: 
    container_name: jinroappcont
    build:
      dockerfile: app/Dockerfile
      context: .
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db
    environment:
      DATASOURCE: jdbc:postgresql://db:5432/jinrodb
  db: 
    container_name: jinrodbcont
    build:
      dockerfile: db/Dockerfile
      context: .
    ports:
      - 5432:5432
    tty: true
