# Docker Composeファイルフォーマットのバージョンを指定
version: '2'

services:
 jinrowebcont:
  build:./web
  image: jinrowebimage:httpd
  ports:
     - 80:80
     -3000:3000
 # 明示的に所属するネットワークを指定する
  links:
     - "jinrowebcont:jinrodbcont"
     - "jinrowebcont:jinroappcont"

  tty: true
  stdin_open: true
  privileged: true
  command: /sbin/init

 jinrodbcont:
  build: ./db
  image: jinrodbimage:postgres
  ports:
    - 5432:5432
 # 明示的に所属するネットワークを指定する
  links:
     - "jinrodbcont:jinrowebcont"
     - "jinrodbcont:jinroappcont"

  tty: true
  stdin_open: true
  privileged: true
  command: /sbin/init

 jinroappcont:
  build: ./app
  image: jinroappimage:openjdk
  ports:
     - 8080:8080
 # 明示的に所属するネットワークを指定する
  links:
     - "jinroappcont:jinrowebcont"
     - "jinroappcont:jinrodbcont"

  tty: true
  stdin_open: true
  privileged: true
  command: /sbin/init