version: '3.9'

services:
  app: 
    container_name: jinroappcont
    build:
      dockerfile: app/Dockerfile
      context: .
    ports:
      - 8080:8080
    links:
      - "jinroappcont:jinrowebcont"
      - "jinroappcont:jinrodbcont"
    tty: true
    stdin_open: true
    privileged: true
    command: /sbin/init
  web: 
    container_name: jinrowebcont
    build:
      dockerfile: web/Dockerfile
      context: .
    ports:
      - 80:80
    links:
     - "jinrowebcont:jinrodbcont"
     - "jinrowebcont:jinroappcont"
    tty: true
    stdin_open: true
    privileged: true
    command: /sbin/init
  db: 
    container_name: jinrodbcont
    build:
      dockerfile: db/Dockerfile
      context: .
    ports:
      - 5432:5432
    links:
     - "jinrodbcont:jinrowebcont"
     - "jinrodbcont:jinroappcont"
    tty: true
    stdin_open: true
    privileged: true
    command: /sbin/init
