# Docker Composeファイルフォーマットのバージョンを指定
version: '3.9'

services:
 web:
 # コンテナ名を明示的に指定する
  container_name: jinrowebcont
  build: C:\Users\81904\ICE202401\repository\jinro-party-server\web
  ports:
          - 80:80
 # 明示的に所属するネットワークを指定する
  networks:
 # ここに指定するのは実際のネットワーク名ではなく、↓のnetworksの識別子
  - container-link

 db:
 # コンテナ名を明示的に指定する
  container_name: jinrodbcont
  build: C:\Users\81904\ICE202401\repository\jinro-party-server\db
  ports:
          - 5432:5432
 # 明示的に所属するネットワークを指定する
  networks: 
 # ここに指定するのは実際のネットワーク名ではなく、↓のnetworksの識別子
         - container-link

 app:
 # コンテナ名を明示的に指定する
  container_name: jinroappcont
  build: C:\Users\81904\ICE202401\repository\jinro-party-server\app
  ports:
          - 8080:8080
 # 明示的に所属するネットワークを指定する
  networks:
 # ここに指定するのは実際のネットワーク名ではなく、↓のnetworksの識別子
  - container-link

 # ネットワーク定義
 networks:
 
  # docker-composeで勝手にデフォルトネットワークが生成される予防。（自動で全コンテナが所属するbridgeを指定）
 default:
  external:
   name: bridge
 # コンテナ間通信用のネットワークセグメント
 container-link:
 # これが作成されるネットワーク名（同名がなければ自動生成される）
 name: jinroparty